name: Build and deploy ASP.Net Core app to Azure Web App - portfolio-uksouth-as

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Build
      run: dotnet build MyPortfolio.csproj --configuration Release --no-restore --warnaserror

    - name: Publish
      run: dotnet publish MyPortfolio.csproj -c Release -o ./publish --no-build

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'portfolio-uksouth-as'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        package: ./publish

    # Optionally, add a step to remove sensitive files from the published output
    # - name: Remove secrets from publish folder
    #   run: rm -f ./publish/appsettings*.json
